### ISSUE TITLE
cuda out of memory

### ISSUE THREAD

**Issue by cuixintong** [zhilin007/FFA-Net#26]
我用作者提供的代码在我的设备上运行main.py,报错内存不足，只有当我把batchsize设置为1时才能运行成功，但是我用的时TeslaV100 32G显卡，作者用的是2080Ti，作者设置的batchsize是16，为什么我的会内存不足呢，有同学遇到这个问题吗

**Comment by Marinerjl** [comment]
你好，我也遇到了这个问题，请问你已经解决了吗

**Comment by cuixintong** [comment]
没有解决，不知道为啥

**Comment by Marinerjl** [comment]
好的，还是非常感谢

**Comment by Marinerjl** [comment]
w = w.view(-1, self.gps, self.dim)[:, :, :, None, None]，我感觉应该是这里的问题，这里把w的维度变成了5维，然后batch_size就非常大了，但是我也不知道要怎么去改，不过也不一定是这个原因，只是我的猜想

**Comment by cuixintong** [comment]
不清楚呀，这个会影响吗，我好奇的是我觉得我的这个32G卡已经挺大了，为什么作者能跑起来 我这不行呢

**Comment by Marinerjl** [comment]
这个问题可能是图像大小的问题，看看图像大小是否为240，我是因为这个原因后来解决了

**Comment by ZhuLiangyu123** [comment]
> 我用作者提供的代码在我的设备上运行main.py,报错内存不足，只有当我把batchsize设置为1时才能运行成功，但是我用的时TeslaV100 32G显卡，作者用的是2080Ti，作者设置的batchsize是16，为什么我的会内存不足呢，有同学遇到这个问题吗
你好，我也遇到了这个问题，请问你解决了吗？

**Comment by xie-xyh** [comment]
您好，我也遇到了这个问题，我试图在kaggle上进行复现，16GB的P100，但也显示CUDA out of memory

**Comment by Longcodedao** [comment]
Hey guys. I think it is quite late to comment on this project. This is my actual debug on my implementation of the model . Since the author used 19 blocks containing the residual networks, the intermediary activations stored in the forward process is extremely high. I have tried the gradient checkpoint for reduce the memory usage, but the memory stored for the backpropagation still cost a lot. I was quite surprised that the author used Batch Size 16 and trained on RTX 2080Ti with 11GB VRAM. What do you guys think? 

```python
class ChannelAttention(nn.Module):
    def __init__(self, dim, hidden_dim, kernel_size=1):
        super().__init__()

        padding = kernel_size // 2
        self.avg_pool = nn.AdaptiveAvgPool2d(1)
        self.ca = nn.Sequential(
            nn.Conv2d(
                dim, hidden_dim, kernel_size=kernel_size, padding=padding, bias=True
            ),
            nn.ReLU(),
            nn.Conv2d(
                hidden_dim, dim, kernel_size=kernel_size, padding=padding, bias=True
            ),
            nn.Sigmoid(),
        )

    def forward(self, x):
        y = self.avg_pool(x)
        y = self.ca(y)
        return x * y


class PixelAttention(nn.Module):
    def __init__(self, dim, hidden_dim, kernel_size=1):
        super().__init__()
        padding = kernel_size // 2

        self.pa = nn.Sequential(
            nn.Conv2d(
                dim, hidden_dim, kernel_size=kernel_size, padding=padding, bias=True
            ),
            nn.ReLU(),
            nn.Conv2d(
                hidden_dim, 1, kernel_size=kernel_size, padding=padding, bias=True
            ),
            nn.Sigmoid(),
        )

    def forward(self, x):
        y = self.pa(x)
        return x * y


# %%
## FFA Block Module
class FFA_Block(nn.Module):
    def __init__(self, dim, kernel_size, bias=True):
        super().__init__()

        padding = kernel_size // 2
        self.conv1 = nn.Conv2d(
            dim, dim, kernel_size=kernel_size, padding=padding, bias=bias
        )
        self.act1 = nn.ReLU()
        self.conv2 = nn.Conv2d(
            dim, dim, kernel_size=kernel_size, padding=padding, bias=bias
        )

        # Pixel Attention
        hidden_dim = dim // 8
        self.pixel_attention = PixelAttention(dim, hidden_dim, kernel_size=1)
        self.channel_attention = ChannelAttention(dim, hidden_dim, kernel_size=1)

    def forward(self, x):
        res = self.act1(self.conv1(x))
        res = res + x

        res = self.conv2(res)
        res = self.channel_attention(res)
        res = self.pixel_attention(res)

        res = res + x

        return res


# %%
# Group Block
class Group(nn.Module):
    def __init__(self, dim, kernel_size, blocks, bias=True, use_checkpoint = False):
        super().__init__()
        self.blocks = blocks
        modules = [FFA_Block(dim, kernel_size) for _ in range(blocks)]
        modules.append(
            nn.Conv2d(
                dim, dim, kernel_size=kernel_size, padding=kernel_size // 2, bias=bias
            )
        )
        self.group = nn.Sequential(*modules)
        
        # We add a flag to control checkpointing
        self.use_checkpoint = use_checkpoint 

    def forward(self, x):
        # We need a wrapper function for checkpoint, since it can't take module as input
        def _group_forward(x_in):
            res = self.group(x_in)
            res = res + x_in
            return res
        
        # Apply checkpoint only if flag is set
        if self.use_checkpoint and self.training:
            # The checkpoint function takes the wrapper and the input tensor(s)
            res = checkpoint(_group_forward, x)
        else:
            # Fall back to standard forward pass
            res = _group_forward(x)
      
        return res


# %%
# Create the FFA-Net Model
class FFA(nn.Module):
    def __init__(
        self, groups, blocks, channels=3, dim=64, kernel_size=3, padding=1, bias=True, use_checkpoint = False
    ):
        super().__init__()
        self.num_groups = groups

        self.preprocess = nn.Conv2d(
            channels, dim, kernel_size=kernel_size, padding=padding, bias=bias
        )
        self.groups = nn.ModuleList(
            [Group(dim, kernel_size=kernel_size, blocks=blocks, use_checkpoint = use_checkpoint) for _ in range(groups)]
        )
        self.channel_attention = ChannelAttention(
            dim * groups,
            dim // 16,
        )

        self.pixel_attention = PixelAttention(dim, dim // 8)

        self.postprocess = nn.Sequential(
            nn.Conv2d(dim, dim, kernel_size=kernel_size, padding=padding, bias=bias),
            nn.Conv2d(dim, 3, kernel_size=kernel_size, padding=padding, bias=bias),
        )

    def forward(self, x):
        x1 = self.preprocess(x)
        res = []

        temp = x1
        for idx, layer in enumerate(self.groups):
            out_group = layer(temp)
            res.append(out_group)
            temp = out_group

        # Shape [Batch, Groups * CHannels, H, W]
        res = torch.cat(res, dim=1)
        weighted_res = self.channel_attention(res)
        weighted_res = rearrange(
            weighted_res, "b (g c) h w -> b g c h w", g=self.num_groups
        )

        # This is mathematically equivalent to: w1 * res1 + w2 * res2 + w3* res3
        out = torch.sum(weighted_res, dim=1)

        # Apply Pixel Attention
        out = self.pixel_attention(out)

        x_out = self.postprocess(out)

        return x + x_out
```

==================== STARTING MEMORY DEBUG 240x240 BS=8 ====================

[MEM] --- Start (Empty Cache) ---
   Active Used: 0.05 GB (Delta: +0.05 GB)
   Cache/Resrv: 0.06 GB
   Peak So Far: 0.05 GB

[MEM] --- After Models Loaded ---
   Active Used: 0.05 GB (Delta: +0.00 GB)
   Cache/Resrv: 0.06 GB
   Peak So Far: 0.05 GB
[INFO] Generator Theoretical Size: 17.00 MB

[STEP] Creating Dummy Batch...

[MEM] --- Input Batch Loaded ---
   Active Used: 0.06 GB (Delta: +0.01 GB)
   Cache/Resrv: 0.06 GB
   Peak So Far: 0.06 GB

[STEP] Generator Forward Pass...

[MEM] --- After G Forward (Activations Stored) ---
   Active Used: 1.07 GB (Delta: +1.02 GB)
   Cache/Resrv: 1.61 GB
   Peak So Far: 1.51 GB

[STEP] Generator Backward Pass...

[MEM] --- After G Backward (Gradients calculated) ---
   Active Used: 0.08 GB (Delta: -0.99 GB)
   Cache/Resrv: 12.19 GB
   Peak So Far: 12.01 GB

==================== DEBUG COMPLETE ====================
